version: '3'
services:
  redis:
    container_name: redis-container
    image: redis:latest
    restart: always
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - 6379:6379
  node-app:
    depends_on:
      - redis
    build: .
    ports:
      - 3001:3001
    links:
      - redis