version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
      - "8001:8001"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis://db:6379
    links:
      - "db"
  db:
    image: docker.io/redis:latest
    